Add Issue MediaType
TrailerVote/trailervote-media-types pull request #6
Opened 2018-10-16 12:24 UTC by VincentRbbmnd

2018-10-16 12:27 UTC, SleeplessByte commented on ruby/lib/trailer_vote/media_types/issue.rb
> +end
EOF newline

2018-10-16 12:27 UTC, SleeplessByte commented on ruby/test/trailer_vote/fixtures/application/vnd.trailervote.issue.v1.create+json
> +}
EOF newline

2018-10-16 12:27 UTC, SleeplessByte commented on ruby/lib/trailer_vote/media_types/issue.rb
> +            merge version_1_base
So you don't get back any timestamp information?

2018-10-16 12:27 UTC, SleeplessByte commented on ruby/test/trailer_vote/media_types/issue_test.rb
> +end
EOF newline

2018-10-16 12:39 UTC, VincentRbbmnd commented on ruby/lib/trailer_vote/media_types/issue.rb
> +            merge version_1_base
`created_at` and `updated_at` are handled by Rails now, so `created_at` is the time the Issue is created on our side.

2018-10-16 12:56 UTC, SleeplessByte requested changes
You probably want to add a `link` to self, because then you don't need to update this media type to add update and destroy via API capability.

You also need to add the issues link to the configuration media type or you won't be able to "know" what the URL is to create issues.

2018-10-17 11:52 UTC, SleeplessByte approved these changes

2018-10-17 12:00 UTC, merged